### ISSUE TITLE
支持if/elseif多条件判断 的疑问

### ISSUE THREAD

**Issue by chenshanhai-mc** [dsc-cmt/cmt-statemachine#13]
是指 `StateMachineBuilder` 构建的时候，能够多条件判断吗？具体是在哪里处理的？

**Comment by WhiteBookMan1994** [comment]
> 是指 `StateMachineBuilder` 构建的时候，能够多条件判断吗？具体是在哪里处理的？

这里的“if/elseif多条件”是指针对同一个 Event，对于不同的 Request 会进到不同的 Transition 中去。简单来说，就是支持一个 Event 对应多个 Transition。代码参见：StateMachineImpl.java 的 routeTransition 方法。
